# Generated by Django 4.1.3 on 2022-11-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_rename_user_votationgroup_candidate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='rol',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='rol',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
