# Generated by Django 4.1.3 on 2022-11-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_candidate_id_alter_rol_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='idRol',
            new_name='rol',
        ),
    ]
