# Generated by Django 4.1.3 on 2022-11-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_rename_idrol_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
