# Generated by Django 4.1.3 on 2022-11-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_user_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votationgroup',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='votationgroup',
            name='start_date',
            field=models.DateField(),
        ),
    ]
